### ISSUE TITLE
Import TPL

### ISSUE THREAD

**Issue by SamuelBreton** [at-internet/gtm-pa-configuration#1]
Can't import the TPL in GTM Import system.
JSON is malformed

![Screenshot_3](https://user-images.githubusercontent.com/569143/199930441-ca5bd3b8-83a9-4867-90e6-014722076464.jpg)

**Comment by BenDz** [comment]
Hey @SamuelBreton, you shouldn't need to import it, the template is available in the gallery, you can add it to your workspace from there: https://tagmanager.google.com/gallery/#/owners/at-internet/templates/gtm-pa-configuration

**Comment by SamuelBreton** [comment]
Effectivement, je cherchais dans les balises.
